### ISSUE TITLE
Possible to change mask?

### ISSUE THREAD

**Issue by sdtacoma** [benaubin/react-headless-phone-input#14]
It it possible to change the input mask?

ie `+1 (512) 555-1234` to `1.512.555.1234`

**Comment by benaubin** [comment]
Hmmm... understood.

I believe the best option would be to pass options to the AsYouTypeFormatter when it is constructed. However, the mask it creates would need to be supported by libphonenumber.

https://github.com/benaubin/react-headless-phone-input/blob/416ebf8f29b3a9952d4f6ca55a1c9988139c0cf7/src/index.tsx#L16-L18

Should be a fairly simple change if it's possible, and I would be happy to accept a PR.
